from cryptofeed.defines import BYBIT, BINANCE_FUTURES, BINANCE_DELIVERY, BINANCE_DELIVERY, BITMEX, HUOBI, BITTREX

ACTIVATE_TRADING = 'ACTIVATE_TRADING'

ORDERS = 'orders'
INSTR_CODE = 'instr_code'
PRICE = 'price'
PRICE_WITH_FEE = 'price_with_fee'
SIZE = 'size'
QTY = 'qty'
PRICE = 'price'
AMOUNT = 'amount'
PRODUCT = 'product'
ORDER_TYPE = 'order_type'
SIDE = 'side'
NEW = 'new'
TRADE = 'trade'

RATE = 'rate'
PREDICTED_RATE = 'predicted_rate'
NEXT_FUNDING_TIME = 'next_funding_time'
LONG = 'long'
SHORT = 'short'

# REDIS FEEDS & KEYS
STATUS = 'status'
STATUS_API = 'status_api'
STATUS_TRADES = 'status_trades'
STATUS_L2_BOOK = 'status_l2_book'
STATUS_FUNDING = 'status_funding'
STATUS_PRIVATE = 'status_private'
STATUS_LIQUIDATIONS = 'status_liquidations'
INSTR_STATUS = 'instr_status'
INSTRUMENT_STATUS = 'instrument_status'
EXCHANGE_STATUS = 'exchange_status'
BOOK = 'book'
ORDERBOOK = 'orderbook'
BALANCE = 'balance'
BALANCES = 'balances'
POSITION = 'position'
POSITIONS = 'positions'
ORDERBOOK_UPDATE = 'orderbook_update'
TRADE_UPDATE = 'trade_update'
CANDLE_UPDATE = 'candle_update'
LIQUIDATION_UPDATE = 'liquidation_update'
BALANCE_UPDATE = 'balance_update'
POSITION_UPDATE = 'position_update'
TRADE_EXEC = 'trade_exec'
ORDER_UPDATE = 'order_update'
EXCHANGE_API = 'exchange_api'
ORDER_EXCHANGE = 'order_exchange'
FUNDING_RATE_UPDATE = 'funding_rate_update'
DB_HANDLER = 'db_handler'
INVENTORY = 'inventory'
DB_STRATEGY_INFO = 'db_strategy_info'
DB_ADD_ORDER = 'db_add_order'
DB_ADD_TRADE = 'db_add_trade'
DB_ADD_LATENCY = 'db_add_latency'
TRIGGER_EVENT = 'trigger_event'
SENTINEL_EVENT = 'sentinel_event'
CANCEL_ORDER = 'cancel_order'
CANCEL_ALL_ORDERS = 'cancel_all_orders'
CANCEL_ALL_ORDERS_INSTR = 'cancel_all_orders_instr'
CANCEL_ALL_ORDERS_ECHANGE = 'cancel_all_orders_echange'

# DB TABLES
STRATEGY_INFO = 'strategy_info'
TABLE_ORDERS = 'orders'
TABLE_TRADES = 'trades'
TABLE_STRATEGY_INFOS = 'strategy_infos'

ID = 'id'
TIME_ACTIVE_MKT = 'time_active_mkt'
EVENT_TYPE = 'event_type'
ORDER_ID = 'order_id'
EVENT_KEY = 'event_key'
MARKET_ID = 'market_id'
TIME_ACK = 'time_ack'
TIME_RECEIVE = 'time_receive'
INSTRUMENT_ID = 'instrument_id'
INSTRUMENT = 'instrument'

EXEC = 'exec'
TIMESTAMP = 'timestamp'
UPDATED_AT = 'updated_at'

# DB INSTRUCTIONS
TABLE = 'table'
ACTION = 'action'
INSERT = 'insert'
BULK_INSERT = 'bulk_insert'
UPDATE = 'update'
SNAPSHOT = 'snapshot'
DELETE = 'delete'

EXCHANGE = 'exchange'
EXCHANGE_NAME = 'exchange_name'
FEED_NAME = 'feed_name'
INSTR_NAME = 'instr_name'
EXCHANGE_ID = 'exchange_id'
SYMBOL = 'symbol'
INSTR_TYPE = 'instr_type'
CURRENCY = 'currency'
TICK_SIZE = 'tick_size'
MIN_ORDER_SIZE = 'min_order_size'
MIN_SIZE_INCR = 'min_size_incr'
CONTRACT_SIZE = 'contract_size'
LOT_SIZE = 'lot_size'
FUNDING_MULTIPLIER = 'funding_multiplier'
MAKER_FEE_ID = 'maker_fee_id'
TAKER_FEE_ID = 'taker_fee_id'
PERCENT_VALUE = 'percent_value'
FIXED_VALUE = 'fixed_value'
STRAT_ID = 'strat_id'
INSTR_ID = 'instr_id'
INSTR_STATUS = 'instr_status'
INSTR_FEED_CODE = 'instr_feed_code'
INSTR_EXCHANGE_CODE = 'instr_exchange_code'
EXCHANGE_ORDER_ID = 'exchange_order_id'
TIME_CANCEL = 'time_cancel'
TIME_FILLED = 'time_filled'
TOTAL_FILLED = 'total_filled'
TIME_TRADE = 'time_trade'
PAYLOAD = 'payload'

LINEAR = 'linear'
INVERSE = 'inverse'
QUANTO = 'quanto'
MOVE = 'move'
BULL = 'bull'
BEAR = 'bear'
HEDGE = 'hedge'
HALF = 'half'

UNDEFINED = 'undefined'
UNKNOWN = 'unknown'
CANCEL = 'cancel'
CANCELED = 'canceled'
SUBMIT = 'submit'
SUBMITED = 'submited'
SUBMITTED = 'submitted'
CLOSE = 'close'
FILL = 'fill'
REJECT = 'reject'
REJECTED = 'rejected'
CANCEL_REJECTED = 'cancel_rejected'
EXPIRE = 'expire'
SEEKER_STATUS_RUNNING = 'running'
SEEKER_STATUS_STOPPED = 'stopped'
EXCHANGE_STATUS_READY = 'ready'
INSTRUMENT_STATUS_READY = 'ready'
EXCHANGE_STATUS_UP = 'up'
INSTRUMENT_STATUS_UP = 'up'
EXCHANGE_STATUS_DOWN = 'down'
INSTRUMENT_STATUS_DOWN = 'down'
EXCHANGE_STATUS_UNAVAILABLE = 'unavailable'
INSTRUMENT_STATUS_UNAVAILABLE = 'unavailable'

IS_REDUCE = 'is_reduce'
IS_REVERSE = 'is_reverse'
IS_INCREMENT = 'is_increment'

RUN = 'run'
START = 'start'
STOP = 'stop'

PUBLIC = 'public'
PRIVATE = 'private'

REGISTERED_EXCHANGES = [
    BYBIT, BINANCE_FUTURES, BINANCE_DELIVERY, BINANCE_DELIVERY, BITMEX, HUOBI,
    BITTREX
]

PING = 'ping'
PONG = 'pong'
