class EventTypes:
    HIT_HIT = 'hit_hit'
    HIT_HIT_FUNDING = 'hit_hit_funding'
    TRI_ARB_SPOT_PERP_FUNDING = 'tri_arb_spot_perp_funding'
    TAKE_HIT = 'take_hit'
    SPREAD_TRIGGER = 'spread_trigger'
    SPREAD_TRIGGER_LIQ = 'spread_trigger_liq'
    SPREAD_TRIGGER_LIQ_WAIT = 'spread_trigger_liq_wait'
    ROLLER = 'roller'
    MM_TRIGGER = 'mm_trigger'
    MM_GRID = 'mm_grid'
    MM_DUMB = 'mm_dumb'
    PAIR_SEEKER = 'pair_seeker'
    TARGET_SEEKER = 'target_seeker'
